# 1.Configuracion del repositorio ✅
# 2. Estrategia de cache ✅
# 3. workflow ✅
# 4. flutter configuration && Java configuration ✅
# 5. Trigger ✅
# 6. flutter analyze ✅
# 7. flutter testing ✅
# 8. flutter build apk ✅
# 9. flutter build ipa ✅
# 10. artifacts ✅
# 11. push firebase app distribution ✅
      

name: fluttermasters
workflows:
  flutter_masters:
    cache:
      cache_paths:
        - "$HOME/.pub-cache"
        - "$HOME/.gradle/caches"
        - "$HOME/Library/CocoaPods"

    environment:
     groups:
       - "Firebase"
     flutter: stable
     java: 11
     ios_signing:
      certificates:
        - FlutterMasterDevelopCertificate
      provisioning_profiles:
        - FlutterMasterProvisionProfile
    triggering:
     events:
       - "push"
     branch_patterns:
       - include: true
         source: true
         pattern: codemagic
  
    scripts:
      - name: INIT KEYCHAIN
        script: keychain initialize
      - name: ADD CERTIFICATES
        script: keychain add-certificates
      - name: SET PROVISIONING PROFILES
        script: xcode-project use-profiles
      - name: FLUTTER ANALYZE
        script: flutter analyze
      - name: FLUTTER TEST
        script: flutter test
      - name: FLUTTER APK
        script: flutter build apk --release
      - name: FLUTTER IPA
        script: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
    artifacts:
      - build/ios/ipa/Apps/alertify.ipa
      - build/app/outputs/flutter-apk/app-release.apk
    
    publishing:
     email:
      recipients:
        - estev97@gmail.com
     firebase:
      firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
      android:
       app_id: 1:927233104549:android:56747debe9c0c55fdc8b4c
       artifact_type: apk
       groups:
         - "testers"

      ios:
       app_id: 1:927233104549:ios:6e7663cbe53d4358dc8b4c
       groups:
         - "testers"
